NUM_GPUS: 1
TRAIN:
  BATCH_SIZE: 50
  EVAL_PERIOD: 500
  CHECKPOINT_PERIOD: 1
  CHECKPOINT_FILE_PATH: '/kaggle/input/ava-heads/slowfast_head.pth'
DATA:
  FEATURE_DIR: "/kaggle/input/ava-npy/"
MODEL:
  NUM_CLASSES: 80
  LOSS_FUNC: "bce_logit"
  HEAD_ACT: "sigmoid"
  MODEL_NAME: "MLP"
SOLVER:
  BASE_LR: 0.01
  GAMMA: 0.1
  STEPS: [50000, 75000]
  LRS: []
  MAX_ITERATIONS: 100000
  MOMENTUM: 0.9
  DAMPENING: 0.0
  WEIGHT_DECAY: 5e-4
TEST:
  BATCH_SIZE: 1024
WANDB:
  NAME: ""
  PROJECT: "AVA"
  RESTORE_NAME: "change this"
AVA:
  TEST_LISTS: ["val.csv"]
  GROUNDTRUTH_FILE: "ava_val_v2.2.csv"
  ANNOTATION_DIR: "/kaggle/input/ava-official/ava_files/annotations"
  FRAME_LIST_DIR: "/kaggle/input/ava-official/ava_files/frame_lists"
  EXCLUSION_FILE: "ava_train_excluded_timestamps_v2.2.csv"
  LABEL_MAP_FILE: "ava_action_list_v2.2_for_activitynet_2019.pbtxt"
  FULL_TEST_ON_VAL: True